### ISSUE TITLE
bug: accessing the array orig at invalid indices

### ISSUE THREAD

**Issue by broukema** [seshnadathur/Revolver#9]
SUMMARY: In src/voz1b1.c the array `orig` can be accessed at
an invalid index, yielding what to the user appears to be a programming
error but in reality is an unwise choice of analysis parameters.

ENVIRONMENT:

*    python2.7
*    Debian GNU/Linux
 *   This bug is present in Revolver commit 792322e

REPRODUCE the bug:

1. Obtain Revolver commit 0af80af in branch `debug_orig_array` and compile:

```
git clone https://github.com/broukema/Revolver.git
cd Revolver
git checkout 0af80af
make
````

2. In your Revolver distribution directory, obtain this N=32^3 T^3 EdS
late-time XYZ ascii snapshot and call it `inputfile.ascii`:

```
wget -O inputfile.ascii.bz2 https://cosmo.torun.pl/~boud/example.EdS.sim.ascii.no.header.norm1.bz2
bunzip2 inputfile.ascii.bz2
```

3. Run revolver.

```
python revolver.py --par=parameters/params.py
```

EXPECTED OUTPUT:

```
Loading parameters from parameters/params.py

 ==== Starting the void-finding with ZOBOV ====
Loading tracer positions from file inputfile.ascii
32768 tracers found
MPI run: calling voz1b1 and voztie to do the tessellation...
Tessellation done.
Post-processing voids ...
Identified 268 potential voids. Now extracting circumcentres ...
Traceback (most recent call last):
  File "revolver.py", line 202, in <module>
    voidcat.postprocess_voids()
  File "/scratch/tmp/Revolver/python_tools/zobov.py", line 1009, in postprocess_voids
    edge_flag = self.find_void_circumcentres(num_acc, wtd_avg_dens, edge_flag)
  File "/scratch/tmp/Revolver/python_tools/zobov.py", line 1078, in find_void_circumcentres
    partadjs[index].append(i)
IndexError: list index out of range

```

The full set of output files (despite the error) is:

``` ls -lR outputs/
outputs/:
total 808
-rw-r--r-- 1 boud boud   4162 Aug  9 16:39 Voids.void
-rw-r--r-- 1 boud boud  12257 Aug  9 16:39 Voids_list.txt
drwxr-xr-x 2 boud boud   4096 Aug  9 16:36 log
drwxr-xr-x 2 boud boud   4096 Aug  9 16:39 rawZOBOV
-rw-r--r-- 1 boud boud    133 Aug  9 16:36 sample_info.txt
-rw-r--r-- 1 boud boud 786436 Aug  9 16:36 test_pos.dat

outputs/log:
total 3788
-rw-r--r-- 1 boud boud 3871578 Aug  9 16:39 test-mpirun.out

outputs/rawZOBOV:
total 1888
-rw-r--r-- 1 boud boud 1227144 Aug  9 16:39 test.adj
-rw-r--r-- 1 boud boud  262148 Aug  9 16:39 test.trvol
-rw-r--r-- 1 boud boud   20868 Aug  9 16:39 test.txt
-rw-r--r-- 1 boud boud    8870 Aug  9 16:39 test.void
-rw-r--r-- 1 boud boud  262148 Aug  9 16:39 test.vol
-rw-r--r-- 1 boud boud  118409 Aug  9 16:39 test.zone
```

ANALYSIS:

The error appears to come from line 348 of voz1b1.c in commit 5954583 on Sep 4, 2018
https://github.com/seshnadathur/Revolver/blob/master/src/voz1b1.c
where `orig` is assumed to have already been assigned an "original" value
for adjacent particle index `adjs[i].adj[j]`. But if the analysis parameters
such as `zobov_box_div` and `zobov_buffer` are not sufficient for this particular
dataset then it's possible for `orig[adjs[i].adj[j]]` to have not been evaluated
at all.

COMMENT:

Adjusting the analysis parameters by setting them to

```
zobov_box_div = 2   # tessellation will be divided into (zobov_box_div)^3 chunks run in parallel
zobov_buffer = 0.1  # fraction of box length overlap between sub-boxes
```

is sufficient to avoid the error and get reasonable results, including a
reasonable looking `outputs/barycentres/Voids_baryC_cat.txt` . But evaluating
an array at an unallocated place in memory is still a bug - the user should be
stopped (and preferably warned) before that happens.

SUGGESTED FIX:

One solution is to record which `orig[.]` members are evaluated, and throw a fatal
error, giving an appropriate warning, if access to an unevaluated member (line 348
of voz1b1.c as stated above) is attempted.

**Comment by seshnadathur** [comment]
fixed as per https://github.com/seshnadathur/Revolver/pull/10
